const routes = require('next-routes')

module.exports = routes()
// .add('home_en','/en')
// .add('home_id','/id')
// .add('project_en','/en/project')
// .add('project_id','/id/project')
// .add('project_detail_en','/en/project/:project')
// .add('project_detail_id','/id/project/:project')
// .add('offices_en','/en/offices')
// .add('offices_id','/id/offices')
// .add('retails_en','/en/retails')
// .add('retails_id','/id/retails')
// .add('resedentials_en','/en/resedentials')
// .add('resedentials_id','/id/resedentials')
// .add('units_en','/en/show-units')
// .add('units_id','/id/show-units')
// .add('about', '/en/about-sato','about-sato')
// .add('tentang', '/id/tentang-sato','about-sato')
// .add('studies', '/en/studies','studies')
// .add('pembelajaran', '/id/pembelajaran','studies')
// .add('intouch', '/en/intouch','intouch')
// .add('intouch_id', '/id/intouch','intouch')
// .add('career', '/en/career','career')
// .add('karir', '/id/karir','career')
// .add('contact', '/en/contact-faq','contact-faq')
// .add('kontak', '/id/kontak-kami-faq','contact-faq')